export const SITE_CONFIG = {
  name: "Ankit Kumar",
  title: "Ankit Kumar | Software Engineering Intern & Full-Stack Developer",
  role: "Software Engineering Intern | Full-Stack Developer",
  college: "ABES Engineering College, Ghaziabad",
  degree: "B.Tech in Computer Science & Engineering",
  cgpa: "7.32",
  expectedGraduation: "2028",
  period: "2024 — 2028",
  location: "Ghaziabad, India",
  phone: "+91 6394802764",
  email: "ay9335144776@gmail.com",
  photo: "/ankit_photo.jpg",
  socials: {
    github: "https://github.com/Ankit-kumar2764",
    linkedin: "https://www.linkedin.com/in/ankit-yadav-6b632b32a/",
    leetcode: "https://leetcode.com/u/Ankit_kumar6394/",
    codechef: "https://www.codechef.com/users/ankit_kumar_76",
    email: "mailto:ay9335144776@gmail.com",
  },
  resume: {
    url: "https://drive.google.com/file/d/1RfNvSm7IFIFQh9WdGTGcgD9J4Xm9_1vy/view?usp=drive_link",
    downloadFilename: "Ankit_Kumar_Resume.pdf",
  },
  tagline: "Computer Science undergraduate with strong skills in Object-Oriented Programming, C++, and full-stack web development. Solved 250+ DSA problems on LeetCode and built production-style applications like the SkyOps Airport Operations Control Center.",
  aboutStats: [
    { label: "LeetCode Solved", value: "250+", detail: "DSA & Problem Solving in C++" },
    { label: "B.Tech CGPA", value: "7.32", detail: "ABES Engineering College" },
    { label: "Hackathons & Events", value: "5+", detail: "Frontend Wars Finalist & Paranox" },
    { label: "Expected Graduation", value: "2028", detail: "B.Tech CSE (2024-2028)" },
  ],
  navLinks: [
    { name: "Home", href: "#home" },
    { name: "About", href: "#about" },
    { name: "Problem Solving", href: "#programming" },
    { name: "Skills", href: "#skills" },
    { name: "Projects", href: "#projects" },
    { name: "Experience", href: "#experience" },
    { name: "Education", href: "#education" },
    { name: "Contact", href: "#contact" },
  ],
};

export const CHATBOT_CONFIG = {
  webhookUrl: "https://jaorfoleujrdsj.app.n8n.cloud/webhook/portfolio-chat",
  botName: "Ankit's AI Assistant",
  welcomeMessage: "Hi there! 👋 I am **Ankit's Portfolio AI Assistant**.\n\nI can answer questions about Ankit's:\n• 🚀 **Projects** (SkyOps Control Center, Care-Scope, Wanderlust)\n• 💻 **Skills & Tech Stack** (C++, React, Node.js, Python, Tailwind)\n• 🏆 **Problem Solving** (250+ LeetCode problems & CodeChef)\n• 🎓 **Education & CGPA** (B.Tech CSE at ABES EC)\n• 📄 **Resume** & 📩 **Contact Information**\n\nHow can I help you today?",
  suggestedQuestions: [
    "Tell me about Ankit",
    "What are his key projects?",
    "What are his technical skills?",
    "How many LeetCode questions has he solved?",
    "Where can I download his resume?",
    "How can I get in touch with Ankit?",
  ],
};
